services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/data/db
    restart: always

  api:
    container_name: orby-api
    build: ./orby-api
    restart: always
    ports:
      - 5002:5002
    depends_on:
      - mongo
    env_file:
      - ./orby-api/.env

volumes:
  mongodb-volume: